# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET

BloggerBlogBundle_list:
    path:     /list/{page}
    defaults: { _controller: "BloggerBlogBundle:Page:list" }
    requirements:
         methods:  GET
# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET
# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_contact:
    path:  /contact
    defaults: { _controller: "BloggerBlogBundle:Page:contact" }
    requirements:
        methods:  GET|POST
# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_blog_show:
    path:  /{id}/{slug}
    defaults: { _controller: "BloggerBlogBundle:Blog:show", comments: true }
    requirements:
        methods:  GET
        id: \d+
BloggerBlogBundle_blog_showcategory:
    path:  /{category}
    defaults: { _controller: "BloggerBlogBundle:Page:list", comments: true }
    requirements:
        methods:  GET
BloggerBlogBundle_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: "BloggerBlogBundle:Comment:create" }
    requirements:
        methods:  POST
        blog_id: \d+

